src/bioregistry/__init__.py, src/bioregistry/data/bioregistry.json, src/bioregistry/resolve.py, tests/test_data.py
=> Begin testing examples

src/bioregistry/app/templates/collection.html, src/bioregistry/data/collections.json, tests/test_data.py
=> Allow multiple authors in a collection

setup.cfg, src/bioregistry/external/__init__.py, src/bioregistry/external/cli.py, src/bioregistry/external/miriam.py, src/bioregistry/external/obofoundry.py, src/bioregistry/external/ols.py, src/bioregistry/external/wikidata.py
This is getting in the way of using the alpine builds of docker Python. It isn't used for anything important so it's getting the boot
=> Remove pandas requirement

src/bioregistry/__init__.py, src/bioregistry/align/obofoundry.py, src/bioregistry/align/ols.py, src/bioregistry/align/utils.py, src/bioregistry/constants.py, src/bioregistry/data/mismatch.json, src/bioregistry/utils.py, tests/test_data.py
This PR introduces another database of mismatches
=> Handle curated mismatches

src/bioregistry/align/cellosaurus.py, src/bioregistry/data/bioregistry.json, src/bioregistry/data/external/cellosaurus/processed.json, src/bioregistry/data/external/cellosaurus/raw.txt, src/bioregistry/data/metaregistry.json, src/bioregistry/external/__init__.py, src/bioregistry/external/cellosaurus.py, src/bioregistry/schema/schema.json, src/bioregistry/schema/struct.py
=> Add cellosaurus registry

src/bioregistry/data/bioregistry.json
=> Add override URL for ena.embl

src/bioregistry/github_client.py, src/bioregistry/utils.py
Since implementing the standardized forms in GitHub, it's now possible to automate updating the bioregistry.
=> Automate adding entries via GitHub issues

.github/workflows/new_prefix_pr.yml, src/bioregistry/github_client.py
Make sure there aren't duplicates, and add a github action
=> Automate pulls

src/bioregistry/align/ols.py, src/bioregistry/app/templates/resource.html, src/bioregistry/data/bioregistry.json, tests/test_data.py
At first point of PR, there are only 45 entries left to do! After these are all done, this PR can be merged and then all entries will require having a homepage.
=> Enforce all non-deprecated entries have a homepage

CODE_OF_CONDUCT.md, README.md, docs/conduct.md
Closes #161 
Questions:
- is this overkill?
- should we make a different email address besides my personal one?
=> Add code of conduct

src/bioregistry/app/api.py, src/bioregistry/app/templates/contributor.html, src/bioregistry/app/templates/contributors.html, src/bioregistry/app/ui.py, src/bioregistry/data/bioregistry.json, src/bioregistry/data/collections.json, src/bioregistry/schema/struct.py, src/bioregistry/utils.py, tests/test_data.py
=> Add tracking of reviewer for prefix

src/bioregistry/__init__.py, src/bioregistry/app/templates/resource.html, src/bioregistry/data/bioregistry.json, src/bioregistry/resolve.py, src/bioregistry/schema/struct.py, src/bioregistry/utils.py, tests/test_data.py
=> Add preferred prefix field

src/bioregistry/data/bioregistry.json
=> Add prefix: pav

src/bioregistry/data/bioregistry.json
=> Update oboInOwl example,, synonyms, and preferred prefix

src/bioregistry/data/bioregistry.json, src/bioregistry/data/external/miriam/processed.json, src/bioregistry/external/miriam.py
Change algorithm for ingesting providers from MIRIAM (they call them resources) to now work this way:
1. Use the "official" one if it's tagged
2. Use the first one in the list otherwise
=> Add providers from MIRIAM

src/bioregistry/align/bioportal.py, src/bioregistry/align/cellosaurus.py, src/bioregistry/align/go.py, src/bioregistry/align/n2t.py, src/bioregistry/align/obofoundry.py, src/bioregistry/align/ols.py, src/bioregistry/align/uniprot.py, src/bioregistry/app/api.py, src/bioregistry/app/utils.py, src/bioregistry/compare.py, src/bioregistry/external/__init__.py, src/bioregistry/external/cli.py, src/bioregistry/external/getters.py, tests/test_web.py, tox.ini
~Stuff is not going well here...~
**update** things are going slightly better
=> Requirement shuffle hotfixes

src/bioregistry/data/bioregistry.json, src/bioregistry/schema/struct.py
=> Fix pattern checking and fix panther.pthcmp pattern

src/bioregistry/constants.py, src/bioregistry/resolve.py, src/bioregistry/resolve_identifier.py, src/bioregistry/resource_manager.py
This is important to make it possible to arbitrarily extend the `get_iri` function
=> Move additional functionality into manager

src/bioregistry/app/templates/resource.html, src/bioregistry/app/ui.py, src/bioregistry/data/bioregistry.json, src/bioregistry/resource_manager.py, src/bioregistry/schema/schema.json, src/bioregistry/schema/struct.py, tests/test_data.py
=> Add extra examples

src/bioregistry/data/bioregistry.json
Closes #306, closes #307, closes #308, closes #309
@matentzn please let me know if these all look okay - not sure if I hit all points for DC for #307
=> Add Nico's updates

src/bioregistry/data/bioregistry.json
good morning bioresigry, we are the bioinformation laboratory( https://sites.google.com/a/ciencias.unam.mx/layla-michan/Home?authuser=0 ) , chairman by the researcher layla michán aguirre, we will be curating and registering the wikidata database.
This is the first addition we make. create the 4dn.biosource database record in wikidata and add it to the bioregistry.json file
=> Add Wikidata database to `4dn.biosource`

src/bioregistry/data/bioregistry.json
This PR changes the github pattern such that it can accept both users/organizations and also repositories. Suggested by @egonw
=> Update GitHub pattern

src/bioregistry/app/templates/resource.html, src/bioregistry/data/bioregistry.json, src/bioregistry/data/external/obofoundry/processed.json, src/bioregistry/external/obofoundry.py, src/bioregistry/schema/schema.json, src/bioregistry/schema/struct.py
=> Add Twitter links

src/bioregistry/data/bioregistry.json, src/bioregistry/gh/github_client.py
=> Add prefix: cpt

.github/workflows/tests.yml, src/bioregistry/curation/add_ontology_regexes.py, src/bioregistry/data/bioregistry.json, tests/test_resolve.py
=> Add patterns for ontologies

src/bioregistry/data/bioregistry.json, tests/test_identifiers_org.py
=> Curation for BridgeDb alignment

.github/workflows/release.yml, .github/workflows/update.yml
@cthoyt 
I guess this should do the trick. 
Btw, I was not able to test it on my fork because of the local changes...
=> Adding automated release

src/bioregistry/data/bioregistry.json
=> Add NIF prefixes

src/bioregistry/data/bioregistry.json
Closes #439 by cleaning up merops and combining disjoint parts of the merops entries namespace together
=> Update MEROPS entries

src/bioregistry/data/bioregistry.json
This PR adds various curations based on the KGOBO dump - it should handle a large number of the missing nodes
CC @LucaCappelletti94
=> Add curations based on KGOBO dump

src/bioregistry/curation/cleanup_authors.py, src/bioregistry/data/bioregistry.json
There might be ragged information about the same person throughout the document, this PR adds a script that does its best to normalize these.
=> Add script for standardizing attribution

src/bioregistry/data/contexts.json
Related to #491
@matentzn this updates the OBO context and needs your approval - it might actually finish the issue #491 completely. Please let me know
=> Use ICD10WHO in OBO context

src/bioregistry/__init__.py, src/bioregistry/app/templates/resource.html, src/bioregistry/app/ui.py, src/bioregistry/data/bioregistry.json, src/bioregistry/resolve.py, src/bioregistry/schema/schema.json, src/bioregistry/schema/struct.py
1. Adds RDF download field (also adds button to website, associated code getter, etc.)
2. Updates ERM
- Adds @egonw as contact
- Add RDF download link
- Add cheminf mapping
- Add twitter
=> Update ERM record

src/bioregistry/data/bioregistry.json, src/bioregistry/schema/schema.json, src/bioregistry/schema/struct.py, tests/test_data.py
Also add missing link to ERM paper
=> Improve provenance data model 

src/bioregistry/app/templates/resource.html, src/bioregistry/gh/new_prefix.py, src/bioregistry/resource_manager.py, src/bioregistry/schema/struct.py
As suggested by @egonw in https://twitter.com/egonwillighagen/status/1564851774565060608, this PR adds the license to the resource page if available. It also does some cleanup for new pydantic warnings in mypy
=> Add license field to web

src/bioregistry/data/bioregistry.json
=> Update the refseq pattern

src/bioregistry/data/bioregistry.json, src/bioregistry/data/external/miriam/processed.json, src/bioregistry/external/miriam.py
I manually ran the alignment with MIRIAM and got some new things, but also a lot of nonsense with prefixes that had random number/letter codes that can't be resolved from the website. Not sure what's going on here so those were excluded.
=> Improve MIRIAM ingest

src/bioregistry/constants.py, src/bioregistry/data/bioregistry.json
This PR annotates more "bananas" where the redundant prefix in the identifier is delimited with an alternate "peel", like a dash or an underscore instead of the typical colon `:`. The following prefixes are affected:
- imex
- mint
- miriam.collection
- miriam.resource
- psipar
Partially addresses #567
| prefix                                                                    | example              | pattern                           |
|---------------------------------------------------------------------------|----------------------|-----------------------------------|
| [`agilent.probe`](https://bioregistry.io/agilent.probe)                   | A_24_P98555          | `^A_\d+_.+$`                      |
| [`amoebadb`](https://bioregistry.io/amoebadb)                             | …
=> Curate some bananas with dashes

docs/curation-blacklisting-external.md, docs/curation.md, src/bioregistry/align/cheminf.py, src/bioregistry/data/bioregistry.json, src/bioregistry/data/external/cheminf/curation.tsv, src/bioregistry/schema/struct.py
Closes https://github.com/semanticchemistry/semanticchemistry/issues/41, closes #257, closes #258
=> Update cheminf alignment

docs/GOVERNANCE.md, docs/curation.md, docs/glossary.md, src/bioregistry/app/templates/base.html, src/bioregistry/app/templates/meta/sustainability.html
This PR makes several documentation improvements:
1. Clarifies publication and attributions in the governance document
2. Adds a nice introduction and table of contents to the "Help Wanted" page
3. Adds introduction text to the section on curating cross-registry mappings
4. Introduces term _Bioregistry_ into the glossary as people who work on/use/support the bioregistry :) 
5. Add several additonal link-outs to the Bioregistry web app as well as some re-organization of links
6. Improve text on project longevity/governance on the Sustainability page of the Bioregistry web app
=> Imrove documentation and web app text

src/bioregistry/data/bioregistry.json
This PR adds a contact and a publication for FamPlex.
=> Add more info to FamPlex

src/bioregistry/data/bioregistry.json, src/bioregistry/data/external/uniprot/curation.tsv
This PR adds a new prefix for UniProt proteomes.
=> UniProt proteome

src/bioregistry/data/bioregistry.json, src/bioregistry/data/mismatch.json
=> Remove misaligned `epo` mappings

src/bioregistry/export/rdf_export.py, src/bioregistry/schema/constants.py
1. Adds cross-references to [IDOT](https://bioregistry.io/registry/idot)
2. Adds ability to annotate parent properties
3. Begin serializing cross-references and parents
4. Add new property for synonym prefixes
5. Begin serializing synonym prefixes
=> Improve RDF export

src/bioregistry/constants.py
Closes #705
Still need to come up with a test scenario for this
=> Remove directory creation

setup.cfg
These are both group IDs used in ROR.
=> Add CNRS and UKPRN

src/bioregistry/app/utils.py, tests/test_web.py
=> Improve handling of invalid formats

src/bioregistry/app/templates/resource.html
=> Add new prefix `emaps`

exports/rdf/schema.ttl, src/bioregistry/export/rdf_export.py, src/bioregistry/schema/constants.py
=> Add additional wikidata xrefs to bioregistry schema

src/bioregistry/data/external/prefixcommons/processed.json, src/bioregistry/data/metaregistry.json, src/bioregistry/external/prefixcommons.py
=> Clean up prefix commons import

src/bioregistry/app/templates/base.html
@cthoyt feel free to edit the description
The icon renders well in tabs
=> Add favicon and meta description in the base.html header

docs/source/conf.py, setup.cfg
Closes #753 as the result of discussion with @JervenBolleman and @cmungall at Biocuration 2023
=> Rename `swisslipid` to `slm`

src/bioregistry/app/templates/resource.html, src/bioregistry/resource_manager.py, src/bioregistry/schema/schema.json, src/bioregistry/schema/struct.py, tests/test_data.py
Please hold of merging. I cannot get the test framework to work locally with Python 3.9 and depend on the testing here.
=> Added Mastodon support

src/bioregistry/data/external/wikidata/processed.json, src/bioregistry/external/wikidata.py
- wikidata updates
- curated stuff
=> Updates for SeMRA

src/bioregistry/app/templates/resource.html, src/bioregistry/app/ui.py
=> Show preferred prefixes on resource page

src/bioregistry/app/templates/base.html
=> Fix type "maitenance"

tests/test_data.py
Closes https://github.com/biopragmatics/bioregistry/issues/938
=> Fix ENA and INSDC Run directionality

src/bioregistry/data/external/miriam/processed.json, src/bioregistry/data/external/miriam/raw.json, src/bioregistry/external/miriam.py, tests/test_data.py
Closes #965
Closes #967 
Closes #966
=> Add PubMed and PMC contact and update PMC information

src/bioregistry/data/external/uniprot/curation.tsv, src/bioregistry/data/external/uniprot/processed.json, src/bioregistry/data/external/uniprot/raw.json, src/bioregistry/external/uniprot.py
The `server` key was renamed to `servers` and is now a list
=> Fix UniProt alignment

src/bioregistry/compare.py, src/bioregistry/export/warnings_export.py
=> Mark three Bgee resources as deprecated

src/bioregistry/app/api.py, src/bioregistry/app/ui.py, tests/test_web/test_api.py, tests/test_web/test_ui.py
Closes #1077 
This addresses the issue @kkaris pointed out, related to #31 and #1037
=> Update reference handling

src/bioregistry/schema/struct.py
Closes #1092
This PR also enables overriding Identifiers.org providers
=> Update GO providers and enable overriding Identifiers.org

docs/CONTRIBUTING.md, docs/_config.yml
=> Improve contribution docs

.github/workflows/tests.yml, src/bioregistry/analysis/paper_ranking.py, tox.ini
1. Add Mastodon prefix
2. improve CRediT
3. improve Publons Researcher ID
4. Enable tox-uv for CI speed up and fix some mypy issues
=> Minor curations and code updates

src/bioregistry/data/curated_papers.tsv
This pull request curates a new publication for the `gold` prefix.
PubMed: https://pubmed.ncbi.nlm.nih.gov/39498478/
=> Add new publication for gold

src/bioregistry/data/curated_papers.tsv
This pull request curates a new publication for the `mobidb` prefix.
It also updates the `homepage` and `uri_format` based on the updated URL provided in the PubMed paper.
PubMed: https://pubmed.ncbi.nlm.nih.gov/39470701/
=> Update mobidb prefix

src/bioregistry/data/curated_papers.tsv
PubMed: https://pubmed.ncbi.nlm.nih.gov/39574394/
Database: https://bfvd.foldseek.com/
This pull request curates a new provider for UniProt: `bfvd`
=> Add new provider for uniprot: bfvd

src/bioregistry/data/curated_papers.tsv
PubMed: https://pubmed.ncbi.nlm.nih.gov/39540428/
This pull request curates a new publication for the `pfam` prefix.
=> Add new publication for pfam

src/bioregistry/data/curated_papers.tsv
This pull request curates 3 new publications for 3 different prefixes.
prefix: string
PubMed: https://pubmed.ncbi.nlm.nih.gov/39558183/
prefix: cath
PubMed: https://pubmed.ncbi.nlm.nih.gov/39565206/
prefix: insdc
PubMed: https://pubmed.ncbi.nlm.nih.gov/39535044/
=> Curate new publications in Bioregistry

src/bioregistry/data/curated_papers.tsv
PubMed: https://pubmed.ncbi.nlm.nih.gov/39535054/
Database: https://markerdb.ca/
This pull request curates a new prefix `markerdb` which provides identifiers for various molecular biomarkers.
This resource is curated without a `uri_format` since the number in the URL for individual entries seems irrelevant and unrelated to the MarkerDB ID associated with each biomarker.
=> Add prefix: markerdb

src/bioregistry/data/collections.json
=> New prefix: `icd11.code`

.github/workflows/tests.yml, src/bioregistry/data/mismatch.json, tox.ini
=> Remove testing on Pydantic v1

src/bioregistry/constants.py
Follow-up from https://github.com/monarch-initiative/mondo/issues/8588
=> New prefix: NORD

pyproject.toml
Upgrade rdflib-endpoint to a version where federated queries from ontotext GraphDB and blazegraph are fixed @cthoyt
=> Improve support for federated queries to the SPARQL endpoint

src/bioregistry/external/cellosaurus/__init__.py, src/bioregistry/external/cellosaurus/processed.json
=> Remove bad URI formats from cellosaurus ingest

src/bioregistry/data/collections.json
@tarcisiotmf is presenting at Biocuration 2025 on the Earth Metabolome Initiative ontology, this PR adds a record for it.
=> Add Earth Metabolome Initiative (EMI) ontology

.github/ISSUE_TEMPLATE/add-collection-prefix.yml
=> Add issue template for prefixes and collections

src/bioregistry/data/collections.json
This was mentioned by Daniel Haft in the talk entitled _Life Cycle Events for Protein Family Models: Birth, Maturation, Cloning, Retirement_ at Biocuration 2025
Next steps: there's a related semantic space in the same URI space for Protein Family Models at https://www.ncbi.nlm.nih.gov/genome/annotation_prok/evidence/NF023550/
=> Add BlastRule

exports/alignment/uniprot.tsv, src/bioregistry/data/collections.json
=> New prefix: antifam

.readthedocs.yml
=> Fix ReadTheDocs configuration

src/bioregistry/data/curated_papers.tsv
This PR curates a new provider for scop: gendis
Website: https://caps.ncbs.res.in/gendis3/home
Pubmed: https://pubmed.ncbi.nlm.nih.gov/40343712/
=> New provider: gendis

src/bioregistry/external/miriam/__init__.py
=> Exclude ChemSpider provider in MIRIAM's InChI record

src/bioregistry/data/collections.json
These describe education levels
=> Add ISCED prefixes

src/bioregistry/analysis/bioregistry_diff.py, src/bioregistry/analysis/mapping_checking.py, src/bioregistry/analysis/paper_ranking.py, src/bioregistry/app/impl.py, src/bioregistry/compare.py, src/bioregistry/curation/add_descriptions_from_gs.py, src/bioregistry/export/rdf_export.py, src/bioregistry/external/integbio/__init__.py, src/bioregistry/external/togoid/__init__.py, src/bioregistry/pandas.py, src/bioregistry/schema/struct.py, src/bioregistry/summary.py, tox.ini
This takes out `skip_install = true` in the mypy section of tox.ini. This means that the Bioregistry package now gets installed, making it possible to type check several more things.
=> Install package during type checking
