docs/_data/contexts/semweb_context.jsonld
src/bioregistry/data/bioregistry.json
src/bioregistry/data/collections.json
src/bioregistry/prefix_maps.py

Closes #52
CC @cmungall note there are a few discrepancies with https://github.com/prefixcommons/biocontext/blob/master/registry/semweb_context.jsonld. 
- `idot` entry is fixed
- `dc` is not given as a duplicate for `dc.terms`
- Some of the other URLs changed as well because they're automatically retrieved from the bioregistry

Add semweb context

---

src/bioregistry/app/templates/access.html
src/bioregistry/app/templates/base.html
src/bioregistry/app/templates/collections.html
src/bioregistry/app/templates/download.html
src/bioregistry/app/templates/metaresources.html
src/bioregistry/app/templates/resources.html
src/bioregistry/app/templates/summary.html
src/bioregistry/app/templates/sustainability.html
src/bioregistry/app/wsgi.py

This PR reorganizes the previous "documentation" pages for the summary and download into several pages. It also adds a new page on "sustainability" which includes a much more detailed description of how the app is managed as well as allusions to some of the discussions we've been having on the OBO Community slack.
@bgyori it would be nice if you could take a look at the text. Probably easiest to deploy the app yourself and read from the browser with:
```shell
$ git clone git@github.com:bioregistry/bioregistry.git
$ git checkout update-meta
$ pip install -e .
$ bioregistry web
```

Update documentation pages

---

src/bioregistry/align/cli.py
src/bioregistry/align/ols.py
src/bioregistry/align/utils.py
src/bioregistry/data/__init__.py
src/bioregistry/data/bioregistry.json
src/bioregistry/data/external/ols/processed.json
src/bioregistry/data/external/ols/raw.json
src/bioregistry/data/ols_processing.json
src/bioregistry/external/__init__.py
src/bioregistry/external/ols.py
src/bioregistry/external/utils.py
src/bioregistry/resolve.py
src/bioregistry/schema/struct.py
tests/test_data.py

This PR takes all of the OLS-specific processing config out of the bioregistry.json file and puts it in its own nice place. It also adds Pydantic models for checking that it's curated properly. Then, it rewrites the OLS aligner and cuts out lots of code necessary for processing version strings from the OLS. Finally, it uses the new unified aligner code

Update OLS processing

---

src/bioregistry/data/bioregistry.json

The ID pattern specified by identifiers.org for `eccode` for higher-level enzyme classes (for instance 1.1.-.-) cannot be resolved (i.e., https://identifiers.org/ec-code:1.1.-.- doesn't work). Bioregistry overrides the ID pattern for `eccode` to `^\d{1,2}(\.\d{0,3}){0,3}$` to allow EC codes like 1.1 but doesn't override the URL resolution, so identifiers.org still blocks resolving e.g., https://identifiers.org/ec-code:1 due to an invalid ID format. This PR updates the resolution URL to fix this.

Override EC code URL

---

.github/workflows/health.yml
README.md
setup.cfg
src/bioregistry/health/__init__.py
src/bioregistry/health/__main__.py
src/bioregistry/health/check_homepages.py
src/bioregistry/health/check_providers.py
src/bioregistry/health/cli.py
tests/test_identifiers_org.py

This PR adds a new directory of scripts that can be run periodically to check the health of the bioregistry (and perhaps other registries, since there are plenty of identifiers.org health scripts I've written)

Add health check scripts

---

README.md
src/bioregistry/__init__.py
src/bioregistry/data/bioregistry.json
src/bioregistry/parse_iri.py
src/bioregistry/resolve.py

While being able to turn IRIs into CURIEs wasn't part of the original goals of the bioregistry, it has most of the metadata that would be necessary to implement such a function.

Add `bioregistry.parse_iri()` functionality

---

src/bioregistry/data/bioregistry.json
src/bioregistry/export/rdf_export.py
src/bioregistry/export/tsv_export.py
src/bioregistry/schema/constants.py
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
src/bioregistry/upload_ndex.py
tests/test_data.py

This PR adds tests to ensure that when we generate a prefix map using the Bioregistry that all of the IRIs are unique. There are two scenarios we can use to mitigate this I can think of offhand:
1. When entries are in parent/child relationship, like `kegg` with `kegg.compound`, `kegg.drug`, etc. we can enforce that the `part_of` annotation is used for all of the children. If only one prefix in a group of prefixes with the same IRI doesn't have a `part_of` relationship, we'll assume it's the parent and default to using it.
2. When entries are annotated with a `provides`, then they will automatically not be considered in the prefix map, such as `ctd.gene`, which provides for `ncbigene`
When neither of these work, this PR has also introduced the `has_canonical` relationship between prefixes …

Add data integrity tests for unique IRIs

---

src/bioregistry/data/bioregistry.json
src/bioregistry/data/metaregistry.json
src/bioregistry/resolve.py
src/bioregistry/resolve_identifier.py
src/bioregistry/schema/struct.py

Closes #177, closes #171, closes #172, closes #173, closes #174, closes #175
This screenshot shows what happens on the DOI page. It now knows how to build scholia pages assuming you mapped the right endpoint in scholia inside the "mappings" field in a given prefix. Interestingly, the Identifiers.org style for adding endpoints like this (e.g., see OLS providers) would be to massively duplicate this, even though there's a single resource that can be handled uniformly. Glad we don't have to do so much duplicate effort!

Add Scholia as external registry

---

README.md
src/bioregistry/data/bioregistry.json
src/bioregistry/resolve_identifier.py
src/bioregistry/schema/struct.py
tests/test_data.py

There were two redundant functions that were getting out of sync, so I deleted one and made improvements on the other. Further, it tries to avoid using identifiers.org lookups (since those snuck in to prefixcommons and GO quite a bit)

Fix resolution lookup

---

docs/img/providers.svg
src/bioregistry/__init__.py
src/bioregistry/app/templates/meta/summary.html
src/bioregistry/app/templates/resource.html
src/bioregistry/compare.py
src/bioregistry/data/bioregistry.json
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
tests/test_data.py

Blocked by #198. Closes #196. This PR does the following:
1. Introduces a new pydantic object and schema for storing information about 3rd party providers that are not considered as resolvers (like Identifiers.org) or lookup services (like the OLS)
2. Provides an example curation from ChEBI - they have many endpoints, including one that generates images. 
3. Incorporates MIRIAM providers that were added in #198
4. Update the resource page on the web app to show extra ones (see image below)
- Import providers in Identifiers.org (but deduplicate ones from OLS, BioPortal, and other resolvers/lookup services)
- Link records that "provide" like ctd.gene
- Consider tagging all providers with types on web interface to reduce confusion between first party default provider, lookup/resolvers, and …

Add provider data model and example

---

src/bioregistry/data/bioregistry.json

@cthoyt, not sure if I did this right. The formatter URL is different, and does not use a prefix in the URL. I tried to learn from the other content, and saw `n2t` under mappings and as separate submap too.

Scholia can resolve Wikidata Q/P identifiers too

---

exports/registry/registry.json
exports/registry/registry.yml
src/bioregistry/data/bioregistry.json
src/bioregistry/schema/struct.py
tests/test_data.py

Some of prefix commons, identifiers.org, etc. refer to other resolvers rather than curating their own stuff. This is a particular problem right now because the UBERON resolution via identifiers.org has broken due to BioPortal changing. The fact that this is 3 levels deep is just not a good look for the Bioregistry. This PR does a few things:
1. Makes sure that the "default URI" is not considered from external resources if they are from a different resolver.
2. Does a few curations to use higher quality resources for resolution
3. Random curations
This PR should supercede #248

Improve generation of default URI format strings

---

src/bioregistry/data/bioregistry.json
src/bioregistry/schema/struct.py

The group responsible for EPIO in the OBO Foundry made a huge mess - they changed the prefix after being listed in the OBO Foundry, and it overlapped with a pre-existing ontology that was not the same (but was in fact also about the same topic, epilepsy). Since the Bioregistry considers OBO Foundry to be pretty high quality and immutable, this required going back and fixing the mappings manually. Unfortunately there is no really good way to guard against this kind of stuff other than petitioning the OBO Foundry to increase its stringency and provide more automated checks for collisions in the future.
Related, I blogged a bit about my frustrations in this regard here https://cthoyt.com/2021/12/17/unique-prefix-picking.html

Clean up EPIO/EPSO entries

---

src/bioregistry/data/bioregistry.json

Closes #287 CC @cmungall 
This PR does several things:
1. Uses the HTTP / dx.doi.org URI format string for the [`doi`](https://bioregistry.io/registry/doi) prefix
2. Adds three alternate providers into the DOI entry corresponding the the HTTPS / dx.doi.org URI format string and both variants of the doi.org URI format string.

Update DOI entry

---

src/bioregistry/__init__.py
src/bioregistry/app/ui.py
src/bioregistry/resolve.py

This endpoint serves a redirect to shields.io for OBO Foundry purposes, but could be extended further

Add health endpoint

---

src/bioregistry/data/bioregistry.json

refs https://github.com/manubot/manubot/issues/282
The example is `2021.07.23.453588`. The following URL resolves this identifier: https://www.biorxiv.org/content/10.1101/2021.07.23.453588. The current `uri_format` results in a broken URL.

Fix bioRxiv URI formatter, add regular expression pattern, and add extra examples

---

src/bioregistry/app/ui.py
src/bioregistry/resource_manager.py
src/bioregistry/schema/struct.py

This pull request adds a metaresolver to the Bioregistry. This does the following:
1. Creates a URI for resolving prefixes inside any registry, as in https://bioregistry.io/metaregistry/obofoundry/GO. This solves two cases:
1. even if it doesn't have prefix-specific pages like cellosaurus, scholia, and NCBI
2. This URI is also appropriate for poorly-behaved resources like N2T whose prefix pages end with a semicolon
2. Creates a URI that's a resolver for CURIEs that use prefixes from each registry, as in https://bioregistry.io/metaregistry/obofoundry/GO:0032571
Under the hood, this maps the registry-specific prefix back to a bioregistry canonical prefix then forwards resolution to the standard resolution endpoint.

Add metaresolver

---

src/bioregistry/align/obofoundry.py
src/bioregistry/external/obofoundry.py
src/bioregistry/resolve.py
src/bioregistry/resource_manager.py
tests/test_acquisition.py

Closes #300
While https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1622 received relatively little interest, this PR automates grabbing information on the OBO Foundry's PURL service configuration repository, which is also on GitHub

Automated getting OBO Foundry examples

---

src/bioregistry/data/bioregistry.json

refs https://github.com/biopragmatics/bioregistry/issues/287
reverts part of https://github.com/biopragmatics/bioregistry/pull/288
The [DOI resolution factsheet](https://www.doi.org/factsheets/DOIProxy.html) specifies that `https://doi.org/DOI` is the preferred format:
> Users may resolve DOI names that are structured to use the DOI system Proxy Server (https://doi.org (preferred)). The resolution of the DOI name in this case depends on the use of URL syntax: the example DOI name doi:10.10.123/456 would be resolved from the address: "https://doi.org/10.123/456". Any standard browser encountering a DOI name in this form will be able to resolve it. The proxy service (both doi.org and the **earlier but no longer preferred** dx.doi.org) is accessible over IPv6, and supports DNSSEC. The proxy …

Use preferred DOI uri_format

---

src/bioregistry/app/templates/resource.html
src/bioregistry/data/bioregistry.json
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
tests/test_data.py

Since I just finished #316, I realized that there wasn't a good way to give credit to people who make modifications after a prefix is minted. This solves that with an extra field.
This PR also adds additional tests for contact, reviewer, and contributor metadata standards.
- DOI has contributors but no submitter
- PAV has a submitter and contributor

Improve credit to contributors

---

.github/workflows/health.yml
.github/workflows/update.yml

refs https://github.com/biopragmatics/bioregistry/issues/320
I was getting a bunch of emails from scheduled workflows failing on my fork. I don't think the scheduled workflows are relevant to forks. Workflow dispatch of these workflows on forks should still be possible.

CI: skip scheduled builds on forks

---

src/bioregistry/data/bioregistry.json

The Bioregistry pulls from many external registries and reuses their content when possible, but sometimes the data becomes out of date or needs to be fixed in the upstream external registries, and their curation teams are slow to respond.
This pull request demonstrates that the Bioregistry can be used to override incorrect/outdated content from those registries.
See also request to Identifiers.org in https://github.com/identifiers-org/identifiers-org.github.io/issues/180

Update GlycoNAVI pattern

---

src/bioregistry/data/bioregistry.json

Motivated by https://github.com/prefixcommons/prefixes/pull/4 and https://github.com/prefixcommons/prefixes/pull/2, this PR adds records for:
- KEGG Reaction Class
- KEGG Drug Group

Additional KEGG Prefixes

---

exports/tables/comparison_goveranance.tex
exports/tables/comparison_goveranance.tsv
src/bioregistry/compare.py
src/bioregistry/constants.py
src/bioregistry/data/metaregistry.json
src/bioregistry/export/cli.py
src/bioregistry/export/tables_export.py
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py

This PR improves the survey on governance for external registries and creates an automatically generated TSV file as well as LaTeX table for use in the paper.

Add first table exports for paper

---

src/bioregistry/data/bioregistry.json

Closes #408 
@bgyori ideally, before merging, we can add a few more examples that failed under the old regular expression from Identifiers.org (`^[A-Z]{2}\\d+([A-Z])?$`) in the `"example_extras"` list field in this record in addition to [USRE38117E1](https://patents.google.com/patent/USRE38117E1). Did you happen to take notes on some that failed?

Update pattern for google.patent

---

exports/registry/registry.json
src/bioregistry/data/bioregistry.json

While discussion about bananas with non-colon delimiters is ongoing, this PR re-introduces the redundant prefixes used in the UniProt local unique identifier patterns. This is likely an artifact of UniProt resources not using CURIE syntax and further the assumption that these are local unique identifiers and not pseudo-CURIEs with respect to an opaque UniProt registry/set of conventions

Update UniProt records

---

src/bioregistry/app/templates/resource.html
src/bioregistry/data/bioregistry.json
src/bioregistry/gh/github_client.py
src/bioregistry/gh/new_prefix.py
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
tests/test_data.py

1. Adds element to resource schema to link to a github issue where it was requested
2. Adds annotations to all requested prefixes via github 
3. Adds badge to web pages
4. Updates the new prefix request pipeline to automatically add future annotations

Add GitHub issue reference to resource schema

---

src/bioregistry/data/bioregistry.json
src/bioregistry/resolve.py
src/bioregistry/resolve_identifier.py
src/bioregistry/schema/struct.py
tests/test_resolve.py

This PR does two things in service of better understanding the situation of namespaces embedded in LUIs and bananas as mentioned in https://syspharm.slack.com/archives/D01QC9NDUCS/p1655239400791709:
1. Does additional curation as a follow-up to to give a full overview of how bananas (both explicitly curated and inferred via OBO Foundry), namespace embedded in LUI (both from MIRIAM and overrides in the Bioregistry), and MIRIAM patterns intersect.
2. Changes automatic generation of bananas for prefixes mapped to OBO Foundry ontologies such that bananas are only automatically generated if the prefix also has a mapping to a MIRIAM/Identifiers.org prefix.
- Adds explicit `"namespace_embedded_in_lui": false` for entries appearing in both OBO Foundry and MIRIAM, but don't have correct namespace …

Cleanup bananas

---

src/bioregistry/data/bioregistry.json
src/bioregistry/data/collections.json

Motivated by the Trello card https://trello.com/c/xzXh2cyJ/4-adding-all-spar-ontologies-in-fairsharingorg, this PR closes #428 by adding the list of SPAR Ontologies from http://www.sparontologies.net/ontologies. Two notes:
1. `foco` and `c2w` were omitted because I couldn't find any links or information to them
2. `pro` conflicts with the Protein Ontology (PR) that has a colloquial synonym of `pro`, so it was given the prefix `puro`. This is an unfortunate inevitability of registries of short prefixes.
After this is merged and the service is re-deployed tonight, these prefixes can be viewed pages like https://bioregistry.io/fabio and this collection will be listed at https://bioregistry.io/collection/0000006.
CC @essepuntato

Add SPAR ontologies

---

src/bioregistry/data/bioregistry.json

OMA provides information about UniProt proteins. I realized this exists when reading through the ontology quality assessment page on https://cthoyt.com/oquat/unknowns/prefix/oma. 
PR pages that shadow UniProt identifiers like https://proconsortium.org/app/entry/PR:Q01112 have links to OMA as if they're xrefs.

Add OMA provider to UniProt

---

src/bioregistry/schema/struct.py
tests/test_data.py

This PR adds a method for the `Resource` class called `get_pattern_re_with_banana` which returns a version of the identifier pattern that matches the embedded namespace (aka banana) in the identifier.
Some example usages:
```python
In [1]: import bioregistry
In [2]: ch = bioregistry.get_resource('chebi')
In [3]: ch.get_pattern_re_with_banana()
Out[3]: re.compile(r'^(CHEBI:)\d+$', re.UNICODE)
In [4]: ch.get_pattern_re_with_banana().match('1234')
In [5]: ch.get_pattern_re_with_banana().match('CHEBI:1234')
Out[5]: <re.Match object; span=(0, 10), match='CHEBI:1234'>
In [6]: ch.get_pattern_re_with_banana(strict=False).match('1234')
Out[6]: <re.Match object; span=(0, 4), match='1234'>
In [7]: ch.get_pattern_re_with_banana(strict=False).match('CHEBI:1234')
Out[7]: <re.Match object; span=(0, 10), …
```

Implement getting pattern with namespace embedded

---

src/bioregistry/app/ui.py
src/bioregistry/parse_iri.py
src/bioregistry/resolve.py
src/bioregistry/resource_manager.py
src/bioregistry/schema/struct.py
tests/test_data.py
tests/test_resolve.py

Closes #482
This enables the following:
```python
>>> from bioregistry import curie_from_iri
>>> curie_from_iri("http://purl.obolibrary.org/obo/DRON_00023232", use_preferred=True)
'DRON:00023232'
```

Improved handling of preferred prefixes

---

src/bioregistry/__init__.py
src/bioregistry/app/api.py
src/bioregistry/collection_api.py
src/bioregistry/export/prefix_maps.py
src/bioregistry/resolve.py
src/bioregistry/resource_manager.py
src/bioregistry/schema/struct.py
tests/test_data.py

This PR exposes `bioregistry.get_obo_context_prefix_map()` for use in https://github.com/INCATools/ontology-access-kit/pull/224.

Make getting obo context prefix map easier

---

src/bioregistry/data/bioregistry.json

Based on discussion with Chris Chute (https://github.com/biopragmatics/bioregistry/issues/251#issuecomment-1097994811), these are the same. Alternative to #485/#486.
@matentzn @joeflack4 thoughts?

Add ICD10WHO as synonym for ICD10

---

src/bioregistry/data/bioregistry.json

As of August 30, 2022 ([ref](https://twitter.com/Cellosaurus/status/1564658792691810305)), Cellosaurus has its own domain name. This PR updates the links but maintains the old one in a legacy provider for backwards-compatibility. 
CC @AmosBairoch @lubianat  
Related: https://github.com/identifiers-org/identifiers-org.github.io/issues/206

Update cellosaurus to new URIs

---

src/bioregistry/data/bioregistry.json

Motivated by https://github.com/identifiers-org/identifiers-org.github.io/issues/207, this PR adds an additional example `10.21/FQSQT4T3` that has a registrant code that's of length 2 instead of 4. It updates the regular expression to better reflect this as well as annotate the banana for MIRIAM backwards compatibility.
I checked out https://www.crossref.org/blog/dois-and-matching-regular-expressions/ to find a better regular expression, but it appears that there's some edge cases that I think it's reasonable to not handle for now.

Update DOI pattern

---

src/bioregistry/data/bioregistry.json
src/bioregistry/data/mismatch.json

Closes #603
This PR does two things:
1. Removes an erroneous mapping to prefixcommons `ptmswitchboard` (I made a companion video explaining how I did this part https://www.youtube.com/watch?v=m-6kYq_8tjQ)
2. Updates the home page

Update UniProt PTM

---

src/bioregistry/data/bioregistry.json

This PR fixes some typos in the description of the AEON (Academic Event Ontology) entry. 
@cthoyt do you want me to make corresponding issue for that?

fix typos in AEON entry

---

src/bioregistry/app/api.py
src/bioregistry/resource_manager.py

This PR adds an API endpoint for generating mappings between external registries' prefixes, with the caveat that it can only handle stuff that's already mapped to bioregistry prefixes.
For example, http://localhost:5000/api/external/mapping/obofoundry/bioportal (later will be https://bioregistry.io/api/external/mapping/obofoundry/bioportal) gives the following summary of OBO Foundry to BioPortal mappings (plus a summary of 27 prefixes only appearing in OBO Foundry and 94 only appearing in BioPortal, of the prefixes from each source that have been mapped to Bioregistry)
<details>
<summary>Click to see JSON</summary>
```json
{
"mappings": {
"ado": "ADO",
"adw": "ADW",
"aeo": "AEO",
"aero": "AERO",
"agro": "AGRO",
"aism": "AISM",
"amphx": "AMPHX",
"apo": "APO",
"apollo_sv": "APOLLO-SV", …
```

External registry mapping

---

src/bioregistry/schema/struct.py

This PR enables two new pseudo-metaprefixes:
1. `bioregistry.upper` which auto-transforms bioregistry keys with uppercase when picking priority prefix
2. `miriam.legacy`, which uses legacy MIRIAM URIs that use HTTP and don't contain prefixes, so for `go:1234567` it would be http://identifiers.org/GO/1234567

Add addition prefix map options

---

src/bioregistry/app/ui.py
src/bioregistry/data/bioregistry.json
tests/test_data.py
tests/test_resolve.py
tests/test_web.py

Closes #660 by adding `c_` as the banana and an empty banana peel. This also updates the resolution workflow to better handle bananas, though doesn't address bananas with colons (re #93) because of issues with lazy colon parsing.

Add banana to `agrovoc`

---

src/bioregistry/cli.py
src/bioregistry/upload_ndex.py

The NDEx package has now gotten out of sync with numpy and checks for `np.float`, which doesn't exist anymore. This PR more generally allows NDEx failures to occur (since issues pop up often) as well as making the typing more explicit so this check doesn't happen.

Improve NDEx uploader

---

src/bioregistry/app/impl.py
src/bioregistry/app/templates/base.html
src/bioregistry/app/templates/home.html

Based on discussion in https://github.com/monarch-initiative/vertebrate-breed-ontology/issues/77, it appears that it wasn't so straightforward to find the new prefix request from the Bioregistry app.

Add additional links for new prefix requests

---

docs/_data/usages.yml
docs/users.md
tests/test_usages.py

This PR adds a manually curated list of organizations/projects/software packages using the Bioregistry in a YAML file and an auto-generated web page to go on https://biopragmatics.github.io/bioregistry

Add page describing usages of the Bioregistry

---

src/bioregistry/app/templates/macros.html
src/bioregistry/app/templates/metaresource.html
src/bioregistry/app/templates/resource.html
src/bioregistry/app/ui.py
src/bioregistry/resource_manager.py

- Add label to resource page about proprietary prefixes 
- Add CURIEs for ontology relations in resource page
- Don't show extra providers in metaregistry table
- If no example/pattern are available, don't double up showing the example CURIE and CURIE patttern boxes

UI Improvements

---

docs/GOVERNANCE.md
src/bioregistry/app/templates/highlights/owners.html
src/bioregistry/app/templates/resource.html
src/bioregistry/app/ui.py
src/bioregistry/data/metaregistry.json
src/bioregistry/export/rdf_export.py
src/bioregistry/resource_manager.py
src/bioregistry/schema/constants.py
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
tests/test_data.py

References #755
1. Adds a data model for identifier space owners. Each resource can have zero, one, or many identifier space owners. Each identifier space owner needs to be identified by a ROR identifier (preferred) or Wikidata identifier. These can be annotated to any record.
2. Resources' identifier space owners can be marked as "partnered", meaning that they have established a more formal relationship with the Bioregistry. The implications of this relationship are TBD.
3. Adds identifier space owners to resouce page (see screenshot below)
4. Adds identifier space owners to RDF export
5. Curates several owners, mostly focusing on big organizations like NLM, NCI, and EBI. Uses `semapv` as the first example of a "partnered" resource
The following screenshot …

Identifier Space Owners

---

src/bioregistry/data/mismatch.json

I have a local script I used to prioritize records that have a contact name and maybe an email, but no ORCID. I did some searching on ORCID for these people.
I also noticed that the `nemo` prefix has bad mismatches, so this record was split.
Some edits I pushed upstream to OBO foundry in https://github.com/OBOFoundry/OBOFoundry.github.io/pull/2321/files
```python
from collections import defaultdict
import click
from tabulate import tabulate
import bioregistry
#: People known to have retired pre-orcid should be skipped
SKIP = {
"Jonathan Bard",
"Vivian Lee", # maybe married and changed name?
}
SKIP_PARTS = {
"helpdesk",
"team",
"customer service",
"administrators",
}
@click.command()
def _main():
data = defaultdict(list)
for resource in bioregistry.resources():
contact = …
```

Add additional contact information and split `nemo` record

---

src/bioregistry/schema/struct.py

Closes #787
This adds Bio2RDF links for all resources that have been mapped to a Prefix Commons prefix so the mapping service can handle bio2rdf URIs. It will now also display on the website too.

Add bio2rdf links

---

.bumpversion.cfg
docs/source/conf.py
setup.cfg
src/bioregistry/__init__.py
src/bioregistry/constants.py
src/bioregistry/parse_iri.py
src/bioregistry/resolve.py
src/bioregistry/resource_manager.py
src/bioregistry/version.py
tests/test_data.py
tests/test_manager.py
tests/test_metaregistry.py

1. Finally removes the `prefix_map` option from parsing URIs/IRIs and bumps by a minor version. Also removes some related code in the public API that was used to support this functionality, including the `ensure_prefix_list()` function. This probably wasn't used by anyone.
2. Consolidates implementation of IRI parsing into the `Manager` class
3. Enables `use_preferred` on the relevant functions as suggested in #790 
4. Updates deprecated testing

Improve CURIE and URI handling

---

.github/workflows/tests.yml
docs/source/conf.py
setup.cfg
src/bioregistry/app/impl.py
src/bioregistry/app/templates/base.html
src/bioregistry/app/templates/meta/access.html
src/bioregistry/app/ui.py
tests/test_web.py

This is in the lead up to switching over to using FastAPI for generating the API. Unfortunately, Flask has dropped py37 support and this is a reminder that flasgger is no longer maintained, and is not smart to rely on.

Remove flasgger

---

src/bioregistry/record_accumulator.py
src/bioregistry/resource_manager.py
src/bioregistry/schema/struct.py
tests/test_data.py

This PR has two parts:
1. It makes sure that if there's a missing primary URI prefix, it skips during record generation
2. Enables setting `bioregistry` as a metaprefix for URI format and URI prefix generation
3. Updates the preferred order for generating URI format strings to use bioregistry instead of other meta-resolvers
4. improves finding URI prefixes - if a higher priority URI format exists, but can't be considered as a URI prefix, then it continues down the priority list instead of quitting
- CC @matentzn this has the effect that 20-30 new terms are getting added to the OBO context that were previously missing

Fix record accumulation

---

src/bioregistry/schema/constants.py

After @egonw shared a link to https://github.com/bridgedb/BridgeDb/blob/master/org.bridgedb.rdf/resources/IdentifiersOrgDataSource.ttl, I realized BridgeDb also has its own RDF vocabulary that overlaps with the Bioregistry Schema, `idot`, and several other semantic web "meta" vocabularies.
this PR adds a prefix for BridgeDb as well as cross-references for its usage to the Bioregistry schema.

Add BridgeDb prefix and map to bioregistry.schema

---

src/bioregistry/schema/struct.py

Fixes #858. My quick benchmark shows that this results in an about 30x speedup when doing a large number of `is_valid_identifier` calls.

Cache compiled re pattern

---

src/bioregistry/app/api.py
src/bioregistry/resource_manager.py
tests/test_manager.py
tests/test_web/test_api.py

There's an API endpoint that lets you get all if the mappings from one external registry to another. For example, getting all mappings from OBO Foundry to Bioportal can be done with https://bioregistry.io/api/metaregistry/obofoundry/mapping/bioportal.
However, the implementation of this functionality is built in to the API route itself. This PR externalizes that implementation into the Bioregistry's manager class so it can be reused.
Related to https://github.com/INCATools/ontology-access-kit/issues/588

Get mappings between external registries

---

.github/workflows/tests.yml
docs/source/conf.py
setup.cfg
src/bioregistry/app/impl.py
src/bioregistry/app/templates/meta/related.html
src/bioregistry/constants.py
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
src/bioregistry/utils.py
tests/test_data.py
tox.ini

As a follow-up to https://github.com/cthoyt/curies/pull/64 (and related to #920 and https://github.com/biopragmatics/bioregistry/issues/899), this PR makes Bioregistry support both Pydantic v1 and v2

Make explicit cross-version support for Pydantic

---

src/bioregistry/app/utils.py
src/bioregistry/resource_manager.py
src/bioregistry/schema/struct.py

Closes #923
Now, the reference page for `edam:data_1153` looks like:

Propogate RDF URI format string to API and update EDAM

---

src/bioregistry/app/templates/metaresource.html
src/bioregistry/app/ui.py
src/bioregistry/data/metaregistry.json
src/bioregistry/resource_manager.py
src/bioregistry/schema/struct.py
tests/test_metaregistry.py

- Improve metaregistry example prefixes
- Ensure that example prefixes in metaregistry are external prefixes (Closes #275)
- Ensure that these actually have mappings 
- Consistently handle mapping external prefixes to bioregistry prefixes in backend
- Handle when external prefix can't be mapped to bioregistry prefiz
- Prefix.cc isn't stored in Bioregistry
- Special case mapping bioregistry to itself
- Various updates to metaregistry

Web application updates following RRID integration

---

src/bioregistry/data/collections.json

This PR adds several records for clinical trial registries listed in https://www.hhs.gov/ohrp/international/clinical-trial-registries/index.html (suggested by @bgyori)
It does not add the following:
1. Tanzania Clinical Trial Registry - I couldn't find on their site where the trial information actually lived
2. Dutch Clinical Trial Registry - they completely stopped maintaining their own and are just part of the WHO effort now, website is down
3. South African National Clinical Trials Register - couldn't get the site to load
Besides the ones added here, the rest are already available!

Add additional clinical trial registries

---

src/bioregistry/data/external/ols/processed.json
src/bioregistry/data/mismatch.json
src/bioregistry/external/ols.py
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
tests/test_data.py

Add field for annotating unresolvable ontologies, update OLS processing, and better annotate HPATH

---

.github/ISSUE_TEMPLATE/new-prefix.yml
src/bioregistry/gh/new_prefix.py

- Activate the ability to add the contributor email
- Add field for publications
- Rename "Repository" to "Source Code Repository" to reduce confusion (people kept putting "bioregistry" as the value for this...)

Improve new prefix form

---

src/bioregistry/data/external/integbio/processed.json
src/bioregistry/external/integbio.py

It turns out that they delete their old dumps and post new ones with a different file name on each release, so this PR adds scraping functionality to get the current download URL.

Fix Integbio downloader

---

src/bioregistry/gh/new_prefix.py

This PR adds a mapping from the issue template yaml to an internal data key allowing to process publications submitted as part of the new prefix request form (which was enabled in https://github.com/biopragmatics/bioregistry/pull/1000). This should fix the error in  https://github.com/biopragmatics/bioregistry/actions/runs/7633346253/job/20795375392.

Fix new prefix action code, add missing publications key

---

src/bioregistry/app/ui.py
tests/test_web/test_ui.py

- Closes #1034 (fixes issue with leading forward slash in ARKs)
- Fixes issue where a colon might appear in the middle of a CURIE that came up in #1032/#1035 for HGVS terms

Improve redirection

---

.github/workflows/update_prefix_cc.yml
src/bioregistry/export/prefixcc.py
tox.ini

References https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1038
Prefix.cc is a website that allows for public curation of CURIE prefix/URI prefix pairs that are useful in semantic web applications. Users can submit new CURIE prefixes, add additional URI prefixes to existing CURIE prefixes, and up- or down-vote URI prefixes for a given CURIE prefix. This can all be done from the website at https://prefix.cc or by its secret API.
To protect from abuse, these actions are limited both on the website and API to one creation and one vote per day. Interestingly, Prefix.cc has an [RSS feed](https://prefix.cc/latest.rss) of when new content is added. It shows that there isn't typically more than one interaction with the underlying database per day. However, Prefix.cc nevertheless has …

Proactively update Prefix.cc

---

docs/health.md
src/bioregistry/health/check_providers.py

This PR fixes an issue where old runs in the Bioregistry health report didn't validate against the current pydantic model. I wrote a script that calculated the missing data and also made "delta" optional since the first item on the list will never have a delta. It also re-runs the health report

Fix Pydantic models for health report

---

src/bioregistry/data/external/miriam/processed.json
src/bioregistry/data/external/miriam/raw.json

The ORDO license is stated as CC BY 4.0 in the ontology
The OBO Foundry patterns need updating since MCRO decided to submit information with a banana to identifiers.org

Add license for ORDO and update OBO Foundry patterns/examples

---

src/bioregistry/app/api.py
tests/test_web/test_api.py

Closes #1065
This PR adds the `/api/uri/parse` endpoint that takes in a `uri` body parameter, and returns some useful information in return
```python
import requests
uri = "http://id.nlm.nih.gov/mesh/C063233"
res = requests.get("http://localhost:5000/api/uri/parse", json={"uri": uri}).json()
```
gives the following:
```json
{
"uri": "http://id.nlm.nih.gov/mesh/C063233",
"reference": {"prefix": "mesh", "identifier": "C063233"},
"providers": {
"default": "https://meshb.nlm.nih.gov/record/ui?ui=C063233",
"rdf": "http://id.nlm.nih.gov/mesh/C063233",
...
}
}
```
cc @rombaum

Add URI parsing endpoint

---

src/bioregistry/app/templates/resource.html

Twitter/X no longer reflects the values of an inclusive and open scientific community, so the Bioregistry isn't going to display organizations' Twitter handles anymore. This PR doesn't delete those from the underlying data - they still might be useful for historical purposes.

Don't display Twitter handles

---

src/bioregistry/data/metaregistry.json

The URL for the BioPortal's icon on bioregistry.io is broken. This PR updates it to a working one.

Broken icon for BioPortal

---

src/bioregistry/analysis/bioregistry_diff.py
tests/test_identifiers_org.py

This script visualizes updates in the Bioregistry given two dates, separating them into two bar graphs—one showing updates in main fields, and one showing updates in fields mapped to other registries.

Bioregistry update visualization script

---

src/bioregistry/data/metaregistry.json

This PR updates malfunctioning logo URLs in the Metaregistry to working ones.

Updated logo URLs in Metaregistry

---

src/bioregistry/data/contexts.json

Most people in the community have moved to using MIM identifiers for OMIM, which we all should. However, some of (like Mondo) have not managed to do that move yet. This change is safe for anyone using the mim strategy.

Update omim.ps preferred prefix to OMIMPS in obo context

---

src/bioregistry/gh/new_prefix.py

This PR refactors the processing of data from new prefix issues such that each issue is processed separately (in a new function separated out from the overall loop) and has error handling around it. This ensures that the Github Action for one issue doesn't fail due to errors in processing a separate issue. Logging is also improved a bit to be more explicit about issues.

Make new prefix issue processing more robust

---

src/bioregistry/external/ols/processing_ols.json

This PR fixes a configuration that is erroring when running update jobs which perform alignment.

Remove version prefix for stato in OLS conf

---

.github/workflows/tests.yml
docs/source/conf.py
pyproject.toml
setup.cfg
src/bioregistry/resource_manager.py

Update documentation build and CI configuration

---

src/bioregistry/schema/struct.py
tests/test_data.py

This PR allows publications to be added to providers of a prefix. This is useful since provider-specific publications don't have a natural alternative place to be curated. Fixes #1207.

Implement object model for provider publications

---

docs/guides/publications.md

This PR adds publication [pubmed:39345624](https://bioregistry.io/pubmed:39345624) to `sgd`.
Unsure whether this should also be included under the publications for `sgd.pathways`.

Add publication for `sgd` and `sgd.pathways`

---

pyproject.toml
src/bioregistry/lint.py

Fixes #1234. More generally, since the web app imports from the cli which in turn imports the linting code, dependencies for linting need to be available in the Docker.

Add pandas as web dependency

---

src/bioregistry/curation/literature.py

This pull request adds the `not_notable` tag to the CurationRelevance vocabulary as a way to mark papers that are relevant for machine learning training but do not meet the threshold for inclusion in the Bioregistry.
While curating papers, there have been a few instances of entries that provide new identifier information but aren't notable enough, or well-maintained enough for inclusion in the bioregistry (https://github.com/biopragmatics/bioregistry/pull/1225). Rather than curating these as subpar prefixes, tagging them as `not_notable` allows us to retain them as positive training samples without cluttering the bioregistry with less impactful entries.

Add `not_notable` to CurationRelevance vocabulary for semi-automated curation workflow

---

src/bioregistry/data/mismatch.json

Remove incorrect fairsharing mapping from `seed`

---

src/bioregistry/constants.py

This PR makes several minor updates to support making a new output of https://github.com/biopragmatics/obo-db-ingest
1. Extend CDDS pattern to allow for unversioned records (i.e., not ending with `\.\d+`
2. Extend COSMIC pattern to allow for dashes
3. Add ability to encode 3.4.24.B15 in EC (see https://www.brenda-enzymes.org/enzyme.php?ecno=3.4.24.B15)
4. Add second letter in MEROPS entry so XM02.001 can be encoded (the M was the issue). This appears in HGNC gene cross-references.

Data updates for obo-db-ingest

---

src/bioregistry/data/curated_papers.tsv

This pull request curates a new publication for 2 existing prefixes in the bioregistry: `intact` and `intact.molecule`. 
This is based on the following PubMed paper:
https://pubmed.ncbi.nlm.nih.gov/39401100/

Add new publication for intact and intact.molecule

---

src/bioregistry/external/alignment_utils.py
src/bioregistry/external/cellosaurus/__init__.py
src/bioregistry/external/cellosaurus/processed.json

Closes #1259
Cellsaurus contains a number of wrong redirects that could be fixed this way..
Test with:
```console
$ python -m bioregistry.external.cellosaurus.__init__
Cellosaurus curated an OBO PURL for `BCGO` that is is missing namespace. See discussion at https://github.com/biopragmatics/bioregistry/issues/1259.                                                                                        
Cellosaurus curated an OBO PURL for `CL` that is is missing namespace. See discussion at https://github.com/biopragmatics/bioregistry/issues/1259.
Cellosaurus curated an OBO PURL for `CLO` that is is missing namespace. See discussion at https://github.com/biopragmatics/bioregistry/issues/1259.
$ bioregistry export
```

Add rule to drop erroneous cellosaurus based redirects

---

src/bioregistry/data/curated_papers.tsv

This pull request curates a new provider for UniProt: `oglcnac`.
PubMed: https://pubmed.ncbi.nlm.nih.gov/39379619/
Database: https://www.oglcnac.mcw.edu/

Add new provider for uniprot: oglcnac

---

src/bioregistry/data/curated_papers.tsv

This pull request introduces four new prefixes for the Synthetic Binding Protein Database (SYNBIP):
PubMed paper: https://pubmed.ncbi.nlm.nih.gov/39413165/
Database: https://idrblab.org/synbip/
- `synbip.sbp`: IDs for the synthetic binding proteins (SBPs)
-  `synbip.bts`: IDs for the binding targets of SBPs
- `synbip.pss`: IDs for the proteins scaffolds of SBPs
- `synbip.epitope`: IDs for the SBP-target complex interactions

Add prefixes: synbip.*

---

src/bioregistry/data/curated_papers.tsv

This pull request curates a new publication for the `refseq` prefix.
PubMed: https://pubmed.ncbi.nlm.nih.gov/39526381/

Add new publication for refseq

---

src/bioregistry/data/curated_papers.tsv

This pull request curates 3 new publications for different prefixes.
prefix: `bindingdb`
PubMed: https://pubmed.ncbi.nlm.nih.gov/39574417/
prefix: `interpro`
PubMed: https://pubmed.ncbi.nlm.nih.gov/39565202/
prefix: `uniprot`
PubMed: https://pubmed.ncbi.nlm.nih.gov/39552041/

Curate new publications in Bioregistry

---

src/bioregistry/app/static/funding-manifest-urls.txt
src/bioregistry/app/ui.py

This adds the ability for external `funding.json` files to point to the Bioregistry, as described in https://floss.fund/funding-manifest/

Add .well-known route for FLOSS/fund

---

exports/alignment/biolink.tsv
src/bioregistry/data/contexts.json

I want to say that this is a compromise I can just tolerate, but I don't really like it. The choice of having `icd11`, `ICD-11` and `ICD11` be associated with the foundation component strikes me as questionable (but I also don't know _for sure_ if this is wrong, else I would insist). What I really do not like is to have `icd11` being the default prefix for the icd11 foundation, rather than the much less ambiguous `icd11.foundation`.
I would say, lets not do any more damage now, this PR will satisfy our immediate needs, but IMO we should just have the icd11 team itself decide what they want. I know them all quite well, and will reach out now to see what they say.

Various updates to ICD 11 prefix record

---

docs/guides/literature_curation.md
src/bioregistry/curation/literature.py
src/bioregistry/data/curated_papers.tsv

This pull request updates the Curation Relevance vocabulary to 
- Expand the definition of `not_identifier_resource` 
- Replace the `no_website` tag with `non_resource_paper`
See https://github.com/biopragmatics/bioregistry/pull/1351#issuecomment-2585363039 for a full explanation of what these tags mean and why they were implemented.

Update CurationRelevance vocabulary

---

src/bioregistry/schema/struct.py
tests/test_data.py

There are few examples of data that have windows-style line returns. This isn't a full fix - the best way would be to update all of the sources to work on this, but is an intermediate that makes sure that the getter methods on the Resource class at least process them out.

Avoid returning windows-style line returns

---

tests/test_data.py

1. Make sure that repository isn't accidentally annotated as `bioregistry` or given not as a URL. Fixes 3 issues here
2. Make sure that emails curated as contacts aren't used that look like group emails (e.g. contains `help@`, `discuss@`)

Add data integrity check for bad emails and malformed repositories

---

.github/workflows/paper_ranking.yml

This pull request modifies the `start_date` and `end_date` variables of the `paper_ranking` pipeline to be set to the first and last date of the month respectively. 
The old variables were simply subtracting 30 days from the start date which was causing it to miss out on ranking papers from the 1st of the month in some cases. 
I also modified the `cron` job to run at midnight EST instead of midnight UTC which is what it was set to previously.
@cthoyt

Adjust the dates for paper_ranking pipeline to be from the first to the last of the previous month

---

README.md
docs/CONTRIBUTING.md
docs/_data/warnings.yml
docs/glossary.md
src/bioregistry/app/templates/meta/access.html
src/bioregistry/resolve.py
tests/test_identifiers_org.py
tests/test_resolve.py

This pull request addresses the following issue: https://github.com/biopragmatics/bioregistry/issues/1404
The following changes are implemented:
- Rename `eccode` prefix to `ec`
- `preferred_prefix` is set to `EC`
- Maintain `eccode` as a synonym
- Update any instances of `provides: eccode` to  `provides: ec`
A few additional files that referenced `eccode` are updated to reflect this change as well.

Rename eccode to ec

---

src/bioregistry/app/templates/resource.html
src/bioregistry/curation/cleanup_authors.py
src/bioregistry/curation/find_contact_groups.py
src/bioregistry/export/rdf_export.py
src/bioregistry/resource_manager.py
src/bioregistry/schema/schema.json
src/bioregistry/schema/struct.py
src/bioregistry/schema_utils.py
tests/test_data.py

This PR adds a slot for multiple reviews, for situations like in #1406 where multiple people gave meaningful feedback and decided on accepting a record
This PR also updates the RDF output to add a few things missed with recent PRs #1389/#1388

New schema element: secondary reviewers

---

src/bioregistry/data/curated_papers.tsv

PubMed: https://pubmed.ncbi.nlm.nih.gov/39373530/
Database: https://idrblab.org/MolBiC/
This PR curates 3 new prefixes for MolBiC which provides identifiers for cell-based molecular bioactivities. There are 3 distinct sematic spaces listed below:
compounds -> `molbic.compound` 
proteins -> `molbic.protein`
cell lines -> `molbic.cell`

New prefix: molbic

---

tests/test_identifiers_org.py

The test condition
```python
for prefix in ["MONDO"]:
self.assertIsNone(bioregistry.get_identifiers_org_prefix(prefix))
```
assumes that MONDO is not in MIRIAM/identifiers.org but it was actually recently added there (https://registry.identifiers.org/registry/mondo) so this test case needs to be updated to a different prefix that doesn't exist there.
This PR updates it to another example that is in a similar group to what MONDO used to be in in that it is in OBOFoundry but not in MIRIAM.
This is necessary to get the new build working as an additional step for #1433.

Update prefix in test to one not currently in MIRIAM

---

pyproject.toml
src/bioregistry/analysis/paper_ranking.py

This PR implements an exclusion list for journals to be used in the automated paper ranking. I added bioRxiv and medRxiv to this list but in principle others can be added if necessary. The PR also simplifies the way we get metadata using a function that upstreams the issue of handling a large number of PMIDs using a function that has been around in INDRA for a while but for some reason not used in this script.
Background: Recently, PubMed is assigning PMIDs to preprints on bioRxiv and medRxiv and these have been showing up in the paper ranking. It is generally not a good idea to curate these as publications associated with Bioregistry entries since any such curation would have to be updated when the paper is published with its stable metadata (title, DOI, PMID, etc. can all change upon …

Exclude preprints from ranking and improve metadata access

---

docs/CONTRIBUTING.md
src/bioregistry/external/alignment_utils.py
tests/test_data.py
tests/test_web/test_api.py

The W3C defines a technical standard for [`NCNAME`](https://www.w3.org/TR/1999/REC-xml-names-19990114/#NT-NCName), which for most intents and purposes is the same as CURIE prefixes. It follows this form:
```
prefix := NCName
NCName := (Letter | '_') (NCNameChar)*
NCNameChar	::=	Letter | Digit | '.' | '-' | '_'
```
1. Adds a data integrity test to make sure all Bioregistry prefixes conform to the W3C NCNAME standard
2. Adds a pattern to the Bioregistry record for itself matching the NCNAME definition
3. Renames the three Bioregistry preixes that aren't conforming, while maintaining the previous prefixes as synonyms:
- `3dmet` (dead resource)
- `4dn.replicate`
- `4dn.biosource`
4. Adds documentation to the contribution guidelines on how to "normalize" prefixes …

Require bioregistry prefixes conform to W3C NCNAME convention

---

src/bioregistry/constants.py
src/bioregistry/parse_iri.py
src/bioregistry/resolve.py
src/bioregistry/resource_manager.py
tests/test_sparql.py
tests/test_web/test_api.py
tox.ini

This PR adds a `on_failure_return_type` option to several parsing-related functions so you can opt into returning `None` instead of `tuple[None, None]`.
This PR also switches from regular 2-tuples to `curies.ReferenceTuple` named tuples for functions that handle/return prefix-identifier pairs.

Improve parsing return types

---

docs/source/conf.py
docs/source/index.rst
docs/source/reference.rst
docs/source/references.rst
src/bioregistry/__init__.py
src/bioregistry/reference.py
src/bioregistry/resolve.py
tests/test_reference.py

This upstreams and improves the Reference class from PyOBO so any library relying on Bioregistry can make sure that its references are either standardized to the Bioregistry's normalized prefixes, or to preferred prefixes.

Add standard references

---

src/bioregistry/data/curated_papers.tsv

This PR curates a new prefix: `phagedive`.
PubMed: https://pubmed.ncbi.nlm.nih.gov/39373542/
Database: https://phagedive.dsmz.de/
It is a database of bacteriophages and archaeal viruses and provides details regarding their taxonomy, host strain, phage morphology, life cycle, origin and genomic data.

Add prefix: phagedive

---

src/bioregistry/data/curated_papers.tsv

This PR adds a new prefix called `gwh` (The Genome Warehouse). The link to the pubmed article and database are below:
https://pubmed.ncbi.nlm.nih.gov/39977364/
https://ngdc.cncb.ac.cn/gwh/
This repository is separated into three categories: Assembly, Coronaviridae, and Poxviridae. This prefix is for the "Assembly" part of the database. Each of the other categories are providers for existing prefixes.

Add prefix: cncb.gwh

---

src/bioregistry/data/curated_papers.tsv

This PR curates a new prefix: `rdbsb`.
PubMed: https://pubmed.ncbi.nlm.nih.gov/39360609/
Database: https://www.biosino.org/rdbsb/
It is a database of catalytic bioparts which provides basic details, function information, and sequence information.

Add prefix: rdbsb

---

src/bioregistry/schema_utils.py
tests/test_curated_mappings.py

This PR fixes an issue in the Pydantic implementation of #1458 where some empty strings need to be converted into None-s when reading the table into an object model.

Handle empty string predicate modifier and comment when reading mappings

---

src/bioregistry/data/curated_mappings.sssom.tsv
src/bioregistry/schema_utils.py
tests/test_curated_mappings.py

This PR adds two fields to the end of the mapping SSSOM file:
1. (optional) Issue tracker / pull request number
2. (required) date of curation
This will make tracking/reporting easier.
Further, this adds stub dates for all of the original curations, and the ones added in the most recent PR

Add date issue and (optional) tracker item to mapping SSSOM

---

src/bioregistry/resolve.py
src/bioregistry/resource_manager.py

This PR adds the `strict` option to the `parse_curie` function

Add `strict` flag to CURIE parsing functions

---

src/bioregistry/data/metaregistry.json

The URL to access records in the Integbio Database Catalog has changed, this PR updates it to one that works well currently.

Fix integbio provider URL

---

src/bioregistry/external/miriam/__init__.py

Fixes #1582 by excluding `modeldb.concept` from import.

Exclude modeldb.concept from import

---

src/bioregistry/constants.py

This PR addresses the issues discussed in #1588 related to inconsistent identifier examples and patterns for the `hogenom` prefix. This is also a blocker for the automated update pipeline.

Update Hogenom examples and pattern

---

src/bioregistry/constants.py

The pattern for `homd.seq` identifiers appears to have changed to include a trailing number, e.g., `SEQF1003.1` resolves but the old example/pattern `SEQF1003` does not resolve. Identifiers.org changed the example to the new convention but hasn't changed the pattern leading to the update pipeline erroring. This PR updates the pattern and example for the current working version as well as the URI format since the old one is not working anymore.

Update homd.seq pattern, example, and URI format

---

src/bioregistry/reference.py
tests/test_reference.py

This enables the following usage:
```python
from bioregistry import NormalizedReference
from pydantic import BaseModel
class Derived(BaseModel):
reference: NormalizedReference
>>> Derived(reference="go:0032571")
Derived(reference=NormalizedReference(prefix='go', identifier='0032571'))
```

Improve usability of derived Pydantic models
